# SITE CONFIGURATION
title: UAF Cyber Security Club
author: UAF Cyber Security Club
description: >
  The UAF Cyber Security Club is a fun and fast paced student-run organization that aims to both teach and learn more about cyber security concepts.

# SEO PLUGIN
social:
  name: UAF Cyber Security Club
  links:
    - https://twitter.com/uafcsc
    - https://github.com/UAFCSC
    - https://facebook.com/uafcsc

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Lectures', link: '/lectures'}
  - {name: 'Events', link: '/events'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Build, Break, Learn

hero_img: uafcsc-2018-atlarge-winners.jpg

email: csc.uaf@alaska.edu

twitter_username: uafcsc
github_username:  UAFCSC
facebook_username: uafcsc
discord_invite: PhPDzNX
google_drive: https://drive.google.com/folderview?id=0B8wWpU2kxwL2S3RUempTMWVkU2M&usp=sharing

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
